name: PR Notification to Telegram
on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 Новый Pull Request в репозитории **${{ github.repository }}**  
            👤 Автор: **${{ github.actor }}**  
            🔗 [Ссылка на PR](${{ github.event.pull_request.html_url }})